spring.application.name=JWT-DEMO
server.port=8081

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=GcxZ5bSKv9QMecu6d/r4+x7+ffj6qmvwR133IBDq+Fc=
jwt.expiration=360